<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NJ0BPAE" failures="1" tests="3" name="TestNGFramework1" time="14.759" errors="0" timestamp="2023-02-23T18:12:04 EST">
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="2.332"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserEmptyPassword" time="0.335">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.exelenter.testcases.LoginTest.validUserEmptyPassword(LoginTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validUserEmptyPassword -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.001">
    <skipped/>
  </testcase> <!-- validUserInvalidPassword -->
</testsuite> <!-- TestNGFramework1 -->
